env:
  global:
    - CC_TEST_REPORTER_ID=0af71489e8a341295574cd43eab4bea0d23dd5477618f96cbc9084bf52395b6b
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.6
install:
    - pip install tox
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
    - tox
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
